### ISSUE TITLE
TEAL - allow backward jumps or indirect jumps

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1211]
TEAL does not allow backward jumps.

This is enforced by the assembler --- https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/assembler.go#L1061 --- and implicitly by the evaluator treating offsets as positive increases in the program counter --- e.g., https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/eval.go#L1078

I believe that TEAL is consciously designed with this limitation in an attempt to ensure that programs do not run arbitrarily long and exhaust computational resources. However, program total execution is separately limited by the cost (`LogicSigMaxCost ` and `MaxAppProgramCost`) so it is not necessary to also restrict the structure of TEAL programs.

If this restriction were removed, then it would be easier to share code in TEAL programs, especially if indirect jumps or `call`/`ret` opcodes were available. If we could share code, then we would be able to decrease the size of TEAL programs.

**Comment by ian-algorand** [comment]
Thanks for bringing this up! @algomaxj and @brianolson have you seen this? Maybe you can talk through this issue here.

**Comment by brianolson** [comment]
(Lots of speculation ahead:) Certainly TEAL will continue to grow and become more capable in the future, and something like this might be possible, it's just a matter of being sure that we can build something that will maintain our reliably high performance system properties. Looping TEAL might be possible in LogicSig context but might not be the right thing in the stateful application context. Or we might build something else entirely to support fully general programming and keep TEAL small for specific uses where it is now.

**Comment by jannotti** [comment]
Just to update on the likely outcome: The existing PR allows existing branch instructions to use negative offsets (to labels), and adds `callsub` and `retsub` that store a return address on a hidden stack, and return to the top address on that stack (and pop it, ofc).  So this does not add indirect jumps.

There is no (data) stack management done on `callsub` and `retsub`.  This means that passing "arguments" is up to the caller and callee to decide upon, but since the return address is on a hidden stack, there doesn't need to be any digging "around it", so that seems easy to manage.

This also means that a "tail-call" is just a branch.  We have not chosen a recursion depth limit yet.

**Comment by jeapostrophe** [comment]
This sounds great :)
