### ISSUE TITLE
TEAL - Add swap

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#1534]
```
a
b
swap
```

is the same as

```
b
a
```

Why not just write `b; a`? Branching!

**Comment by jeapostrophe** [comment]
I can add it, but don't want to go through the effort if you'll reject it.

**Comment by brianolson** [comment]
Hi Jay, I think you're suggesting adding a `swap` opcode that would swap the last two elements on the stack. It's certainly a common feature in stack languages. I think TEAL works around this in part by use of `store`/`load` and the scratch space. `swap` can be achieved in 4 instructions: `store 1; store 2; load 1; load 2`. I've been able to work around the lack of `swap` with things like that and changes to the order of sections of the program. It's certainly fine to have this on the backlog of requests for the next major version of TEAL. Since we just released a major upgrade to TEAL recently it will probably be a few months before the next batch of additions.

**Comment by jeapostrophe** [comment]
TEAL is like a chip from the 1970s. It has <1k of ROM and an 8-bit address space. I think the only way to effectively program it is to use the "CISC" mentality from that era and have opcodes which conserve space and have a lot of functionality in them. Your proposed replacement for `swap` requires giving up two addresses forever to code generation and takes 8 opcodes rather than 1. Something like that would be fine if code size were not scarce.

**Comment by brianolson** [comment]
It is very much like an 8 bit micro, with a sha256 accelerator ;-)
Yeah, `swap` is a good idea, but it'll still likely be a few months before the next batch of TEAL improvements.

**Comment by jeapostrophe** [comment]
Implemented in #1640

**Comment by jannotti** [comment]
Added. To appear in Teal3.
