### ISSUE TITLE
Consider Reflecting Subsystems on Filesystem

### ISSUE THREAD

**Issue by lazaridiscom** [algorand/go-algorand#186]
## Is your feature request related to a problem? Please describe:

I'm (nearly) always frustrated when source-code is flat, simply because this makes "diving-in" more difficult.

## Describe the solution you'd like:

Standard System-Design-Principles:

=> Systems should be broken down into subsystems

### Example

https://github.com/algorand/go-algorand/tree/master/agreement

=> Add (at minimum) folders "proposal" and "vote" (containing relevant source-code)

=> Add a README to those folders

**Comment by Vervious** [comment]
It is certainly a goal to break down the agreement package. The proposal and vote code, however, probably shouldn't be in separate packages, by nature of the agreement protocol.

**Comment by lazaridiscom** [comment]
The thing is that the "agreement" directory contains far too much files. And it becomes immediately clear that proposal/vote should be grouped in a folder:

proposal( => 12 files

vote* => 11 files

this is more or less a no-brainer.

**Comment by Vervious** [comment]
we're talking golang style packages here, and need to make sure the right interfaces are exported and exposed. vote and proposal talk to each other, a lot, to the extent that I think they should not be split. It's hard to draw an interface there. If you have a proposal for such an interface, please share it.

If we want to split up the agreement pkg we should do it across a different boundary.

Big packages aren't inherently a bad thing, have you seen `go`'s `runtime` pkg?

**Comment by derbear** [comment]
I think the general sentiment expressed in this issue is a worthy one (decomposing the agreement package), but I don't think it's very actionable. 

Additionally, I think the specific idea of separating `proposal` and `vote` is inherently a bad one. It is true that packages are meant to encapsulate subsystems, but why should proposals and votes be in different subsystems? They are both implementation details of the consensus protocol, and as such, they should not be exposed to external modules.

As a result, I'm closing this issue. Please reopen it if you have a concrete counter-proposal for what the a different package interface looks like.

**Comment by lazaridiscom** [comment]
@Vervious , @derbear , please reread the issue. It's about "Consider Reflecting Subsystems on Filesystem", and a simple example was given.

Your current structure is simply to flat. It makes a dive-in difficult, and essentially it's a violation of basic system-design-principles.

I mean, **one** folder with 70 files in its root? => Congratulations! I really expected more from an MIT offspring.

Your thinking is bound to "Go, Packages", but I'm talking about "Subsystems" and "Folders", which can help break down larger subsystems to further subsystems.

Additionally, i cannot reopen this issue myself. Closing issues that fast will (I assure you) alienate any newcomer.



May I ask who's the person responsible for the overall architecture and the developer-experience?

**Comment by Vervious** [comment]
@lazaridiscom it looks like you have never worked in golang before. The package structure exactly mirrors the subdirectory structure, and is a unit of organization.

We closed this issue because it is un-actionable, and made a single proposal targeting consensus code, that if we chose to act on, would make the agreement code less readable, more complicated, and strictly worse. 

We agree that we should try to divide complex packages into smaller, encapsulated units of functionality that are well tested. That is a given, and always a goal.

Please consider re-evaluating your proposal in the broader ecosystem of go development. We are happy to reopen the issue or engage on a new one if you have concrete proposals that align with golang code quality and style.

**Comment by lazaridiscom** [comment]
> The package structure exactly mirrors the subdirectory structure, and is a unit of organization.

I see. Another google-DX-tragedy

>> May I ask who's the person responsible for the overall architecture and the developer-experience?

Is this a secret?

> Please consider re-evaluating your proposal in the broader ecosystem of go development.

see #191
