### ISSUE TITLE
Update Mobile Endpoints to 2.3.1-beta3

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/go-algorand#1915]
## Summary
The mobile services endpoints need to be updated to 2.3.0-beta3

## Scope/Requirements
The db needs to be migrated to match 2.3.0-beta3 and the pods need to be upgraded

## Urgency/Relative Priority
This needs to be done asap to support the mobile dev team

**Comment by onetechnical** [comment]
prod cluster betanet is on 2.3.0-beta2, and will need to be reset. (This is because 2.3.0-beta upgrades were broken, and the database will need to be rebuilt.) Since it's a complete rebuild, we can either dump and import the beta database from the internal cluster, or we can work with the 2.3.1-beta3 database.

**Comment by onetechnical** [comment]
Broken out into separate ticket https://github.com/algorand/go-algorand-internal/issues/1002
