### ISSUE TITLE
Port all auction e2e tests from go-algorand to auction repo

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#205]
Further regression testing is needed for   GOAL2-445 BLOCKED  
https://github.com/algorand/auction-tools

Specifically, at least, end to end tests still need to be ported from go-algorand to auction-tools.

**Comment by winder** [comment]
@ian-algorand @rotemh 
I just noticed this ticket, and the link to the auction-tools. Currently, that repo is private, should it be made public? For the time being I had left it private since there were some production blockers, like this ticket, and unresolved go-algorand-sdk dependencies/design comments. Should I update the README with comment about the state of things, and make it public?

**Comment by ian-algorand** [comment]
old issue, deferring
