### ISSUE TITLE
AVM: Provide a logging or transaction return value feature

### ISSUE THREAD

**Issue by chaihoang** [algorand/go-algorand#2349]
AVM code should be able to write information that is committed into the block

**Comment by jannotti** [comment]
Let's call it `log` so that Ethereum uses have a rough idea what its intend purpose is.  It will be an opcode that takes one "bytes" stack argument.  It can be called up to 8 times in a program, and log up to a total of 1k bytes.  This is similar to how we spec ApplicationArgs, though only half as large.

For events, perhaps we will recommend that the bytes first four bytes is a hash of an event name, and the rest is an encoding of some values, as the ABI recommends for tuples.

For return values, the ABI encoding can be used. In deference to the recommendation about events, perhaps the recommendation should be that return values are encoded as hash("return") || encoding(value). That is, some constant 4 bytes that identifies this log message as the return value, followed by the usual ABI encoding.

At some point, it should become possible for later txns in a group to see the log messages from previous txns in the group.

**Comment by shiqizng** [comment]
@jannotti how much should this opcode cost?

**Comment by jannotti** [comment]
> @jannotti how much should this opcode cost?

I think the default, 1, is fine.  My reasoning is that it is not computationally expensive, and we don't charge for txn size, we just maintain limits (1k, here).
