### ISSUE TITLE
[Design first] Mobile global infrastructure for failover

### ISSUE THREAD

**Issue by yaovi-a** [algorand/go-algorand#2411]
**Problem:** 

We currently don't have a process around how failovers are leveraged during a mobile failure.
What we do have are global endpoints to absorb those failures when they do occur. 

**Acceptance criteria:** 

What is the process for promoting endpoints in the event of a failure?
Given a scenario, there should be failure process around the expected outcome of the failure. 
Output stories that will execute on these proposed processes.

**Comment by bricerisingalgorand** [comment]
Catastrophic RDS failure test plan:

* Start global indexer set up in two regions
* Disable network access to RDS on primary region
* Promote secondary regional cluster to primary
* Start indexer writer in secondary region
* Run indexer data validator script

**Comment by bricerisingalgorand** [comment]
https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/2190868499/Multi-Region+Failover

**Comment by onetechnical** [comment]
This is only with regards to the mainnet db, I presume, since the all-global db should contain the rest.

I think you're lowballing the Global RDS Failover feature cost; I think an archival node will cost more, especially if we account for redundancy and multi-versions. (We will still need to support deployments to it.) My guess is that this is probably more in the $750-$1000/month range at cheapest for full redundancy. Editing the scripting to support this failover will also take some work. The 10-20 minute failover time feels like a non-starter, though.

I also think you're lowballing the redundant regional RDS outside US-East-2. Also, while I appreciate the need for low latency to global resources, I feel like we would get more bang for our buck in us-west-1 or something, since the vast majority of our traffic is US-oriented.

It also seems strange to me that we wouldn't consider adding transaction nodes outside the US as well as part of this scheme, though maybe that can be reserved for a future change.

**Comment by bricerisingalgorand** [comment]
> This is only with regards to the mainnet db, I presume, since the all-global db should contain the rest.
> 
> I think you're lowballing the Global RDS Failover feature cost; I think an archival node will cost more, especially if we account for redundancy and multi-versions. (We will still need to support deployments to it.) My guess is that this is probably more in the $750-$1000/month range at cheapest for full redundancy. Editing the scripting to support this failover will also take some work. The 10-20 minute failover time feels like a non-starter, though.
> 
> I also think you're lowballing the redundant regional RDS outside US-East-2. Also, while I appreciate the need for low latency to global resources, I feel like we would get more bang for our buck in us-west-1 or something, since the vast majority of our traffic is US-oriented.
> 
> It also seems strange to me that we wouldn't consider adding transaction nodes outside the US as well as part of this scheme, though maybe that can be reserved for a future change.

I only talked about mainnet in this doc because I think that's the only one that would be worth the money to keep running in the event of an emergency. I'm not sure it's worth the extra ~850/month to run the archival nodes for betanet or testnet to keep those running during an outage since they don't get a lot of use.

Thanks I just realized I didn't include the ebs price. I just added the cost of two 1.5 tb volumes. The redundant RDS shouldn't actually require any script changes since it's just changing the db url. We'll just need to do a deployment of indexer readers with that db url. Since we'll be maintaining both the blue/green databases, whichever color is staging won't make a difference.

I think using us-west-1 might be a little dangerous, since this plan is for handling catastrophic errors in us-east-2 which would also include ec2 or eks outages as well. So there's a good chance in the event we actually have to use this, only the ap-northeast-2 cluster is accessible to users.

We have the transaction node failover through the secondary regions, so if us-east-2 goes down users will automatically be routed to ap-northeast-2 and vice versa.

**Comment by bricerisingalgorand** [comment]
Here are tickets I made for follow up work

https://github.com/algorand/go-algorand-internal/issues/1487
https://github.com/algorand/go-algorand-internal/issues/1486
