### ISSUE TITLE
Straightforward "view" or "pure" app calls

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#2520]
It should be easier to ask an algod to execute a txgroup purely to see the results (that is, the blockchain is not written to at all).  This is akin to dry-run, by would use the current state of the blockchain rather than expect state to be supplied. Dry-run is aimed at debugging, while this feature is intended to allow dapps/wallets to "execute" app calls to get an answer (but not modify state).  This is a "view" function in Ethereum.  Further, apps might not even inspect state for some calls, those are "pure" functions.  Both should be "callable" without fee.

**Comment by brianolson** [comment]
This also sounds like the way DryRun works in the AWS API, checking against the world as it is to see if the action is possible. Thinking of it this way I'd want to call _this_ 'dry run' and the old 'dry run' feature be renamed to 'debug' or 'simulate'.

**Comment by jeapostrophe** [comment]
Agree and I like the renaming.

These view functions could have a higher cost budget since we know they won't run in the critical time region and it would be even nicer if there were a way to have more space for the code for these also, although I don't know how practical that would be... maybe an App could have a 32 byte hash of extra code that could be submitted at the same time as the dry run where the on-chain code is a prefix of that. Maybe 96 bytes to be able to store it on IPFS. Something like that.

**Comment by jannotti** [comment]
This is a reasonable way to do it: https://github.com/algorand/go-algorand/pull/2506

**Comment by barnjamin** [comment]
This would be _awesome_

**Comment by algoanne** [comment]
doing this work in #3953 and potential follow-ups there.
