### ISSUE TITLE
Goal remote node config

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#2904]
## Problem

When getting started, goal is often the easiest method to start sending transactions.  This ease is complicated by the need to have a node installed to get config/make requests.

## Solution

Allow a config option for an Algod client that makes requests to a remote API.

@nullun pointed out that the algod.net file has the ip/port for a REST api.   Pointing it to `algoexplorerapi.io:443` worked to get node status on the cli after tweaking: 

```
ben@LAPTOP-4EV1BSD6:~/go/src/github.com/algorand/go-algorand$ git diff
diff --git a/nodecontrol/algodControl.go b/nodecontrol/algodControl.go
index d6aed9f4..b180dfd4 100644
--- a/nodecontrol/algodControl.go
+++ b/nodecontrol/algodControl.go
@@ -86,7 +86,7 @@ func (nc NodeController) ServerURL() (url.URL, error) {
        if err != nil {
                return url.URL{}, err
        }
-       return url.URL{Scheme: "http", Host: addr}, nil
+       return url.URL{Scheme: "https", Host: addr}, nil
 }

 // GetHostAddress retrieves the REST address for the node from its algod.net file.
 ```

```sh
ben@LAPTOP-4EV1BSD6:~$ cat .algorand/algod.net
algoexplorerapi.io:443
ben@LAPTOP-4EV1BSD6:~$ goal node status
Last committed block: 16279285
Time since last block: 1.2s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/abc54f79f9ad679d2d22f0fb9909fb005c16f8a1
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/abc54f79f9ad679d2d22f0fb9909fb005c16f8a1
Round for next consensus protocol: 16279286
Next consensus protocol supported: true
Last Catchpoint: 16270000#QK7RJHDC6FDDZ3QR4M5IDOSWXPD4XEQQP7ARI3EHKHVWRWOXMQQQ
Genesis ID: mainnet-v1.0
Genesis hash: wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=
ben@LAPTOP-4EV1BSD6:~$ goal asset info  --assetid 438831
Error processing command: json: cannot unmarshal array into Go struct field Account.assets of type map[uint64]v1.AssetHolding
```

It looks like the rest client has a number of the endpoints hardcoded to v1 endpoints/data structures
https://github.com/algorand/go-algorand/blob/4b675629252d6f14e206998f4fba235eebc2023b/daemon/algod/api/client/restClient.go#L361-L401

I haven't tested all the endpoints yet.

## Dependencies

goal, libgoal

**Comment by jannotti** [comment]
It is possible to "trick" goal by creating a directory with algod.net and algos.token in it. That should certainly be made easier by using environment variables or command line switches to supply address and token.

To really ease getting started, goal probably also needs a way to accept private keys for signing operations, rather than always expecting a kmd to talk to.

**Comment by barnjamin** [comment]
>It is possible to "trick" goal by creating a directory with algod.net and algos.token in it. That should certainly be made easier by using environment variables or command line switches to supply address and token.

yep, got this _sort of_ working by just pointing to algoexplorerapi.io but there are a number of functions expecting v1 algod payloads. I can start to run thru them if you think this is worthwhile.

> To really ease getting started, goal probably also needs a way to accept private keys for signing operations, rather than always expecting a kmd to talk to.

I figured a local KMD assumption would be _ok_, easier to setup than a node. But happy to see anything that would make it even easier to setup

**Comment by jannotti** [comment]
I'm reluctant to change one hardcoded protocol (http) for another (https). An option: If ALGOD_ADDRESS and ALGOD_TOKEN environment variables are set, then prefer them to the files in the datadir, and, in fact, don't require a data directory at all. (Obviously, so of the commands `goal` supports need a datadir, like `node start`, but many do not.)

Switching to v2 is somewhat orthogonal, but I guess the issue is that some public algod providers have v1 turned off?

Some other ways that goal could be improved to help new users.
- Allow specifying keys (either base64 encoded, or by mnemonic) for signing operations, rather than require kmd.
- Break goal out of repo so that it is `go get` installable
- Have a command line switch for many commands that cause them to emit their info in json, so it's scriptable.

**Comment by barnjamin** [comment]
These are great ideas to improve goal especially for new devs.

I expect that to rip out goal would need some design considerations to be discussed, maybe internally?

How should I proceed on this? File some more issues? Just start hacking?

**Comment by jannotti** [comment]
My personal opinion is that removing the need to specify `-d` for some operations, and instead get the info from the environment (or other switches, like `--algod-token`, `--algod-address`, `--kmd-token`, `--kmd-address`) would make a nice self-contained PR that could be accepted on its own.

I think that's also true of v1 -> v2 (as a separate PR though).

The other ideas (allow specifying keys, make goal go gettable) would probably need considerably more buy-in, so I wouldn't jump into working on them.  I think you could make issues, with as much detail as possible, and that might be the first step in getting that buy-in.

**Comment by brianolson** [comment]
Env var `$ALGORAND_DATA=foo` currently exists as an alternative to `goal -d foo`; extending that along with extending other ways of specifying net&token makes sense to me.

**Comment by jannotti** [comment]
But that var requires you set up files to "trick" algod.  You have to
create a directory, and create files to hold the token and address.  It's
pretty weird if your real intent is just to make `goal` talk to an
internet accessible `algod` instead of a local one.  Also, algod.net only
has the host and port, it's presumed to be `http`. An ALGOD_ADDRESS var
would probably contain the protocol. (I suppose that would be the truly
smallest useful PR - make it so algod.net can specify the protocol if it
wants, so at least the "trick" works)

I have noticed as I browse goal source that it would be super invasive to
make the earlier ALGOD_ADDRESS change I recommended, by the way.  We use
the datadir all over the place as a way to pass around a lot of context -
how to contact kmd, algod, etc.

**Comment by daoarchitect** [comment]
+1. Developing locally against a node using shell scripts and goal is integral to our workflow. We have a private node running on a hosting provider that we can only currently interact with via the SDKs, which is not ideal for the prototyping stage of our contracts, so we have resorted to spinning up local networks and populating them with the requisite accounts and assets in order to test out specific contracts.

**Comment by Blackglade** [comment]
+1 to this as well. It would be a great quality of life improvement.

**Comment by algochoi** [comment]
PR to migrate the goal client from v1->v2 might allow goal to use remote v2 providers: https://github.com/algorand/go-algorand/pull/4684

**Comment by win-t** [comment]
Hi, I created this PR https://github.com/algorand/go-algorand/pull/4922
I hope it can help this issue, although it is not an elegant solution
