### ISSUE TITLE
Support secp256r1 curve in ECDSA verification opcode

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#2959]
follow-up to [2852](https://app.zenhub.com/workspaces/algorand-main-workspace-5ea71fda6d554d53dda36f16/issues/algorand/go-algorand/2852). 

In this ticket, add support for the secp256r1 curve.  

Benchmark and compare cost to secp256k1 (if higher, will have to update the cost of the opcode).

**Comment by jannotti** [comment]
Keep in mind that our opcodes must have a single cost, so if there is a different cost for these curves (I don't really think so?) then we either need to pick a compromise value (if they are close), or make a new opcode (if they are far apart), or make it so that this kind of opcode's cost can be field dependent (more work, and slightly more complex cost model going forward).
