### ISSUE TITLE
Assembly Error Message

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#3082]
## Problem

When using the API to compile a teal contract, if there is a syntax error or something else the error returned is a generic "%d error(s)" with no hints on what it might be.

The assembler does have some list of the errors but summarizes them with a count here:
https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/assembler.go#L1676-L1682

Is this done for a specific reason or could we return some string with all the error messages or at least the first N?

**Comment by algochoi** [comment]
I think the discrepancy is because in the `goal clerk` command, [`ReportProblems()`](https://github.com/algorand/go-algorand/blob/8ff58cb6573e6e36f63b7a1571c7a198e75b099d/data/transactions/logic/assembler.go#L2113) is explicitly called and returns the error array to `stderr`. 

However, it seems like we do not do this for the [`/teal/compile/` API endpoint yet](https://github.com/algorand/go-algorand/blob/8ff58cb6573e6e36f63b7a1571c7a198e75b099d/daemon/algod/api/server/v2/handlers.go#L746). We call `assemble()`, which only returns the number of errors in a program. If we could also report the error array here, I think it would save a lot of devs trouble 😅
