### ISSUE TITLE
goal asset create - support manager, reserve, freeze, and clawback

### ISSUE THREAD

**Issue by AustP** [algorand/go-algorand#3361]
## Problem

When creating an asset, the transaction structure supports specifying the manager, reserve, freeze, and clawback accounts. The `goal asset create` command doesn't allow us to specify those fields, however.

## Solution

Add flags like `--manager` etc. to the create command.

## Dependencies

No

## Urgency

Not urgent, but nice to have.

**Comment by jannotti** [comment]
I agree.  Any chance you'd be interested in doing a PR?  It _appears_ straightforward.  See `createAssetCmd` in goal/asset.go.  Compare it to `configAssetCommand` which takes `--new-freezer` (and others).

Something to be aware of.  The current code sets them all to creator because that's "safe" in the sense that they can then be changed to something else by the manager.  You don't want to set them to 0 just because a flag for, say, the freeze addr is missing.  A zero address can never be changed. You probably want an explicit flag like `--no-freezer` for such a case.  So each address would get two flags - one to set it, and one to make it the zero address.  Else continue to set it to the creator.

**Comment by Priegle** [comment]
resolved in #3369
