### ISSUE TITLE
/v2/teal/disassemble fails to decompile an application

### ISSUE THREAD

**Issue by mxmauro** [algorand/go-algorand#4040]
### Subject of the issue

`/v2/teal/disassemble` returns bad request for a code that can be decompiled with dryrun endpoint.

### Your environment

Node version: 3.6.2

### Steps to reproduce

1. The base64 encoded approval program of application `204329956`, created on block 13527360 is: `AyAFBgIEAAEmBCDE3VmWTHdnsyTkjA99scami/OrFUfc781XL+wZnuDyUgFzAWwBaDEQIhJEMSAyAxJEMQAoEkQxGEEAGTIEIxJEMRkkEkQpJRYCZyoyBmcrJWdCAAsyBCEEEkQxGSUSRCEEQw==` (You can verify by calling `GET /v2/blocks/13527360` or [here](https://algoexplorer.io/tx/ZEH4DH7TYGKOC64FMIIL2UE5RTJGKWFA6BKUS5FBPGWMQWPGTFGQ))
2. Convert the base64 data into a binary file.
3. Call `POST /v2/teal/disassemble` with the binary file as the body.

### Expected behaviour

To get the decompiled TEAL

### Actual behaviour

Got `{"message":"intcblock ran past end of program"}`

**Comment by algochoi** [comment]
The `/v2/teal/disassemble` endpoint takes the program bytes instead of the Base64 encoded data as input (see: https://github.com/algochoi/go-algorand/blob/91095fa6bdccb11ec133c38da68fdd92fa611b6c/daemon/algod/api/algod.oas2.json#L1441) 

Hope this clears things up - also interested in hearing if you (or others) think that base64 encoded files should be supported.

**Comment by mxmauro** [comment]
Hi @algochoi my wrong.

Data I was passing was indeed the binary but using `--data` instead of `--data-binary`.

Thanks a lot for the quick reply. Closing this.
