### ISSUE TITLE
Resolve fast catchup bug

### ISSUE THREAD

**Issue by algoidan** [algorand/go-algorand#4497]
## Context

If the SP chain is stuck, my online node is behind, and I fast catchup too far ahead of the last on-chain State Proof, I won't be able to sign the stuck State Proof. Fast catchup only provides the node with 320 rounds of lookback data, so the ledger will be missing information (online balances, txn commitments, etc) required to assemble & sign the SP message.

If this node has meaningful stake, their missing signature could impact the ability to recover the stuck SP chain.

## Details
If the last confirmed SP was for round N, and I fast catchup to round N + 320 + 256 (or more), I won't be able to sign the SP for N + 256 because I won't have the necessary VotersForRound from the ledger for N. The ledger only stores a 320 round lookback (on a normal node operation the history gets extended if needed) from the round you fast caught up to. 

This issue might be ignored so we will just fix the node expectations.

**Comment by gmalouf** [comment]
@algoidan any updates on this one/potential resolution?

**Comment by algoidan** [comment]
This issue affects participating nodes that use fast catchup. This node will not be able to sign the previous state proof message. (It will be able to sign the following).

As part of the recoverability work, we can solve this. However, I'm not sure it is worth it, but I can be convinced otherwise.
I will add a possible solution to the design doc.

**Comment by algonoah** [comment]
Closing this as won't fix - rare edge case that only impacts situations where
1. The SP chain is stuck while the main chain advances on
2. There is an online participant who is currently behind the stuck SP chain
3. This online participant uses fast catchup to jump at least ~576 rounds beyond the stuck SP chain
4. They have enough stake to meaningful contribute to resuming the stalled chain

We can prevent this issue by having the participant use catchup instead of fast catchup.
