### ISSUE TITLE
Remove genesis id

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#49]
Summary: Now that genesis hash is required, we can remove genesis id. We can perform a protocol upgrade that removes the genesis ID. This change affects what’s in transactions and reduces complexity of new transactions.

Note: There's a protocol upgrade associated with this task so we want to account for testing time

**Comment by zeldovich** [comment]
I don't think this is necessary or a good idea.  It's not necessary because genesis ID is already optional and doesn't have to be included in transactions.  It's not a good idea because genesis hash (the other way of identifying which chain a transaction belongs to) isn't directly human-readable, and genesis ID provides a human-readable sanity-check that users can perform when verifying a transaction they're about to sign.

**Comment by ian-algorand** [comment]
@derbear can you jump in here?

**Comment by derbear** [comment]
It's not necessary, but it adds complexity to have two different ways of isolating blockchains and also to transaction verification. I would rather get rid of genesis ID and instead map the genesis hash to a human-readable string (like we do for mnemonics).

**Comment by zeldovich** [comment]
Do we know if there are pre-signed transactions for future rounds that include genesis ID?

**Comment by ian-algorand** [comment]
We don't know the answer to Nickolai's question. Maybe @Priegle or @ejbaran would know?

**Comment by ejbaran** [comment]
Yes there are. We should keep genesis ID.

**Comment by derbear** [comment]
It's already backwards-compatible, so making this change would lose us the backwards-compatibility. It looks like we'll need to maintain support for genesis ID then.

**Comment by Vervious** [comment]
(Sounds like we won't/shouldn't fix. If I'm wrong, please re-open.)
