### ISSUE TITLE
Add Scratch slots usage to the trace

### ISSUE THREAD

**Issue by algoanne** [algorand/go-algorand#5013]
See [Epic](https://github.com/algorand/go-algorand/issues/4969) for context. 

At each step of the trace during an app evaluation, if a Scratch slot's value was altered, include that information in the trace: which Scratch slot it is and what the new value is. 

one subtlety: if a Scratch slot is assigned 0 (or the same thing it had before), this won't show up as a delta. Are we ok with this as a limitation of the trace output? Probably yes - in dryrun, every time it sends you the entire state of the scratch slots. It's using an efficient encoding for when there are lots of 0's. 

For the simulate trace, we would prefer to send the delta than the entire set of scratch slots.

**Comment by FrankSzendzielarz** [comment]
Whats the plan then?

**Comment by algoanne** [comment]
@FrankSzendzielarz the trace will include transaction#, PC#, and the stack. Other information like local/global state changes and scratch slots can be derived from that info + the teal. We debated what should be included in this trace object vs. further up the stack. We settled on this simple trace as a primitive. When we get into the debug adapter protocol, we will likely include scratch slot info there

**Comment by FrankSzendzielarz** [comment]
Who is "we" and why werent other stakeholders (eg me) involved. This additional compromise means additional complexity for upstream components. Why? What is the justification of duplicating logic the AVM already implements? Now for functionality like resetting the execution cursor the debugger needs to know avm semantics, add in the line by line state, and now you have 2 components to maintain for the same functionality. If a state operation is faulty in testnet, the debugger wont show it, or vice versa.  It is leakage and duplication of reaponsibility.

**Comment by algoanne** [comment]
you would use the DAP instead, which should offer the interface needed so that downstream consumers don't need to worry about AVM semantics etc (that's our goal!). This should make it _simpler_ for consumers than putting everything in a weird trace object that is specific to Algorand. I hope that makes sense? 

And "we" did include some downstream stakeholders, sorry I didn't include you too - but thankfully I think the decision wasn't contentious in the end. Once we all thought it through it felt obvious

**Comment by FrankSzendzielarz** [comment]
So the DAP will be part of Algod or by using the Algod components linked and built simultaneously? So why have an exported half baked trace file at all? So who is developing this DA because as we discussed and as I was informed this is my roadmap task, so me being omitted from the discussion is a bit of a screw up. By someone.

**Comment by algoanne** [comment]
@FrankSzendzielarz well this is all recent anyway, we're in the middle of working on the trace. So we can meet now to revisit with you and make sure this altered plan works for you too?

**Comment by FrankSzendzielarz** [comment]
You are proposing that 3rd party debug adapters act as simulators of the AVM for a percentage of the AVM behaviour and the rest will be fully described by some trace file. I mean I might be wrong but this just strikes me as unjustifiably poor software design. What if a test version of a future version of the AVM has a bug.... The debug adapter is just going to guess? I mean I would need to see the justifications for this kind of software design because at first glance it seems insane

**Comment by algoanne** [comment]
From my understanding (might not be perfect): 

In a more standard execution environment, the debugger would be moving the actual execution forward or backwards, giving that responsive experience devs are used to. 

In our environment it's quite difficult to do that, but using an execution trace allows us to _simulate_ a debugger experience. The trace collects the necessary execution information during the simulate execution. However, how do we interpret the trace? It's not the standard debugger interface at all. Hence why we need to implement the DAP ourselves - the DAP is the translation from the trace to the debugger UI. 

We could include more information in the trace (the Scratch slots, the global/local/box state, possibly more things), but that actually wouldn't necessarily help. The debugger would still not know what to do with the unfamiliar trace object and how to deliver an expected user experience from it. The debugger would in fact still need to understand some aspects of how the AVM work. 

This is why separating the jobs between the trace and the DAP made sense to us this way: The trace collects the actual execution information, the minimum necessary. The DAP we build will (using its AVM knowledge) interpret the trace and provide a standard debugger interface from it. 

Does that makes sense?

**Comment by FrankSzendzielarz** [comment]
The whole idea of using a DA was something I introduced around about Christmas, in the assumption that the new Algod debug endpoints would support interactive debugging (register breakpoint, request state, move execution cursor etc). Instead your team decided to offer a trace file. My task then became to develop a DA that would have to compromise and only offer the illusion of interactive debugging, by stepping into a trace file. This is a PITA and crap UX for devs because now breakpoints set in the SC will mean that when the SDK makes an app call txn it is has to detect if the debugger is attached and decide if to call Simulate again or v2/transactions, and when stepping out of the app call do the actual txn submission. This compromise also means the trace file has to record the state deltas at each program counter. However now to add insult to injury the decision was made, without my involvement, to exacerbate this even more by chucking out the state deltas and duplicating the AVM in the DA.

**Comment by algoanne** [comment]
@FrankSzendzielarz I'm sorry I didn't involve you in the latest discussion, that was an oversight on my part (it can be challenging to always involve all the right people in an open-source ecosystem!). I'm a little surprised to hear you didn't like the original plan we had discussed together... is it all worth another live conversation? As I said, we're currently developing the trace and everything we did on it so far had to be done anyway, so no harm done technically.

**Comment by winder** [comment]
FWIW we've been talking about debug adapter protocols for a while.

![image](https://github.com/algorand/go-algorand/assets/125509/60cf2dba-2bc7-4d6f-b28b-543dbf6f4736)

Some thoughts in no particular order.
* Realtime debugging is more familiar, on this point we are in complete agreement.
* With realtime debugging, you can modify variables at runtime, this cannot be done with the trace file solution. Are there any other debugging features we lose as a result of this design? I couldn't think of any.
* The trace file approach is a little unusual, I really disliked it at first because it seemed weird.
* The trace file approach allows you to step programs forwards AND backwards, which is pretty neat. Not sure my debuggers support that though, they usually only have a step forward button.
* The trace file approach allows you to debug transactions without running algod locally, this may be nice in some scenarios.
* The trace file reminds me of a core dump - so maybe the unusual thing is that we're describing it as a debugging instead of a trace dump.
* I really don't see how this would impede a good UX. Why would it be any different from a normal debugger?
* You mentioned debugging multiple transactions in a row. I'm not sure how that would work in a live debugger. Wouldn't they be rejected from the block moments after the execution is paused?

**Comment by FrankSzendzielarz** [comment]
If the DA was parr of algod i dont see why execution dump would be needed at all. Yes debuggers allow you to arbitrarily move the execution cursor. The issue with the UX is that when authoring a system such as a web app and wanting to put a breakpoint on a backend SC the SDK has to be aware if the IDE debugger is attached in order to route the Transaction call to Simulate to launch the DA and the developer needs to be aware that having stepped in the transaction did not execute, and that if they want to continue the debug session the SDK needs to offer the option of firing off the transaction before resuming the IDE. The trace file approach is still somewhat tolerable but then removing state deltas from it makes no sense at all.

**Comment by winder** [comment]
Why does the IDE need to know if it's attached or not? When I debug, I'll typically set breakpoints prior to starting a test or running the program (and then be annoyed months later when debugging unrelated code when the old breakpoints are triggered).

I'm not following the part about the SDK firing off a transaction. Doesn't the trace file makes that whole thing simpler? You fire off the transaction and then have a trace to debug. Or are you thinking about cases where there are app calls in multiple transaction groups? Maybe this trace thing needs to support concatenating multiple traces.

I forgot about things like "step over" and "jump to cursor", they've never been part of my workflow. Thanks for reminding me about that.

From what Anne mentioned above, it sounds like the trace file is practically an implementation detail and that they prefer to think of the DAP as the interface you would use. My team isn't building it though, someone else would need to weigh in about the actual deliverable and how they expect it to be used.

**Comment by FrankSzendzielarz** [comment]
The IDE does not need to know. The SDK does. If my C# client calls an ABI method I want the SC breakpoint to be hit. The proxy client calling thr ABI method does so via an app call transaction. This call is done using an SDK. The SDK in this context needs to detect if the IDE debugger is attached to the process and then NOT call v2/transactions but Simulate. Then when leaving , either by completion or debugger detach or whatever, the actual txn needs to be submitted (or not, perhaps). In any case the whole flow is just weird. I know there is this resistance to having a dev mode node 'halt' for any reason but basically i think it should and the Simulate endpoint should be unrelated to debugging. My deliverable is to produce a DA. I originally expected some sensible API from algod but instead, to my disappointment, was told a trace file would have to do. Now the trace file is being cut down and the DA is supposed to be a part AVM to compensate. I should not have to explain to anyone why this idea is totally dumb
