### ISSUE TITLE
Performance test follow mode.

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand#5128]
## Problem

We need to understand the performance characteristics of follow mode. How much slower is it than traditional catchup? (ideally it's not slower).

Specifically, how quickly can a state delta be retrieved for each round and how much latency does it introduce compared to a standard catchup.

Suggested approach: Write a shell script to:
- run regular Mainnet catchup with a regular node. 
- run regular Mainnet catchup in follow mode while calling state delta, with default max account lookback (4). 
- run regular Mainnet catchup in follow mode while calling state delta, with max account lookback = 16. 
Result metric: "node reaches round 20,000,000 after X minutes"

Alternatively, to test this, we could run two different configurations of Conduit: 
- algod importer in archival mode
- algod importer in follow mode

**Comment by Eric-Warehime** [comment]
Some quick scripts and corresponding test results: https://gist.github.com/Eric-Warehime/f7a637ec851160e62b8f2db1d23ce481

My sample size is 1 and I only did the first 10k rounds on mainnet so it's just empty blocks but I don't think that really matters since we're just trying to see how the sync mode affects the catchup service.

In summary, for the first 10k rounds on mainnet:
* Regular catchup took ~100 seconds.
* Sync mode catchup w/ default `MaxAccountLookback` took ~1073 seconds
* Sync mode w/ [`MaxAccountLookback`](https://github.com/algorand/go-algorand/blob/master/config/localTemplate.go#L475) = [`CatchupParallelBlocks`](https://github.com/algorand/go-algorand/blob/master/config/localTemplate.go#L222) = 16 took ~326 seconds


So caching more rounds and allowing the catchup service to properly pipeline obviously is very significant.
Also of note, the faster we can update the sync round the close we can get to regular catchup time. So I think it's probably going to be more efficient to rely on retries in the importer than calling wait-for-block-after for every round. I didn't take the time to write retries into the bash script.

Next steps: Look at the importer to see if we can use retries on the delta endpoint instead of having to call `wait-for-block-after` for every round.

**Comment by Eric-Warehime** [comment]
A few rounds of tests led to the following conclusions:  
* `Wait-for-block-after` is much faster than any retry w/ backoff strategy attempted (and backoff time is very important since ~3% of block requests in follow mode get 404 responses. 3% of 27 million round mainnet catchup = 810,000 retries)
* Altering the APIs can make this more efficient w/ fewer round trips. E.g. combining block and delta into a `/v2/validated-block` endpoint, or setting sync round as a side effect of retrieving delta info, etc.
* Adding concurrency to the conduit pipeline (similar to Indexer's old blockqueue) should get us back to around where we were pre-conduit.
