### ISSUE TITLE
docker: Permission errors on mounted volume

### ISSUE THREAD

**Issue by joe-p** [algorand/go-algorand#5464]
### Subject of the issue

The UID and GID are set in such a way that it can be difficult to work with mounted volumes. Out of the box on Ubuntu and Alma the container will fail to run because it doesn't have permissions in `/algod/data` if it's a mounted volume. Providing an explicit set of UID:GID also causes permission errors. 

Similar issues also occur with podman as well. 

### Your environment

Docker: Docker version 24.0.2, build cb74dfc

Tried on both Ubuntu 22.04.2 LTS and AlmaLinux 9.1. Output below is from Ubuntu

### Steps to reproduce

```
$ docker run -it --rm -v ./data:/algod/data -u $UID:$GID algorand/algod
Starting Algod Docker Container
   ALGORAND_DATA:  /algod/data
   NETWORK:        
   ALGOD_PORT:     8080
   FAST_CATCHUP:   
   DEV_MODE:       
   TOKEN:          Not Set
   KMD_TOKEN:      Not Set
   TELEMETRY_NAME: 
   START_KMD:      Not Set
sed: couldn't open temporary file /node/run/sedaudUzI: Permission denied
```

```
$ docker run -it --rm -v ./data:/algod/data algorand/algod
Starting Algod Docker Container
   ALGORAND_DATA:  /algod/data
   NETWORK:        
   ALGOD_PORT:     8080
   FAST_CATCHUP:   
   DEV_MODE:       
   TOKEN:          Not Set
   KMD_TOKEN:      Not Set
   TELEMETRY_NAME: 
   START_KMD:      Not Set
Created new rootkey: /algod/Wallet1.rootkey
Created new rootkey: /algod/Wallet2.rootkey
Created new rootkey: /algod/Wallet4.rootkey
Created new rootkey: /algod/Wallet3.rootkey
Generating Wallet1's keys for a period of 30000 rounds
Generating Wallet2's keys for a period of 30000 rounds
participation key generation for Wallet2 completed successfully
participation key generation for Wallet1 completed successfully
https://github.com/algorandfoundation/specs/tree/44fa607d6051730f5264526bf3c108d51f0eadb6 100000
Created 4 new rootkeys and 2 new partkeys in 1.308298966s.
NOTICE: Participation keys are valid for a period of 30000 rounds. After this many rounds the network will stall unless new keys are registered.
 ** failed ** - Preserving network rootdir '/algod'
Error creating private network: open /algod/data/genesis.json: permission denied
```

### Expected behaviour

Container is able to run without needing to manually set directory permissions

### Actual behaviour

`chmod` or `chown` must be manually used to allow the container's user to write to the directory

### Solution?

Why does the container attempt to run with its own UID and GID? Seems to me the easiet solution is to not manually override the UID/GID and just let the container daemon handle this as per usual.

**Comment by winder** [comment]
Hi Joe, this is the pattern used by postgres and redis containers. At the time of this change my understanding was pretty good but now I'm struggling a bit to recall the details. IIRC the core issue is that we don't want to run as the root user, but do need to write files in the data directory. With the configuration we have, it works by default on a normal machine. With a restricted distro that totally prevents running as root, you need to set the UID/GID and also set the mounted directory to the same UID/GID. Since you already have to jump through some hoops on a restricted machine, we opted for the solution that postgres/redis uses so that it works on normal machines without anything special. 

For reference, take a look at [the issue we were tracking](https://github.com/algorand/go-algorand/issues/5255) when making the UID/GID 999/999 change. and also some comments in the [pull request](https://github.com/algorand/go-algorand/pull/5276).

Additionally, take a look at the "Arbitrary --user Notes" section here: https://hub.docker.com/_/postgres/

This is also covered in the "Mounting the Data Directory" section of our docker documentation: https://hub.docker.com/r/algorand/algod

**Comment by joe-p** [comment]
> we opted for the solution that postgres/redis uses so that it works on normal machines without anything special.

The problem is that it's not working on "normal machines". I encountered this on fresh installs of Ubuntu 22 and Alma 9.1 (granted they are Hetzner install images, but mostly vanilla). On Alma I even completely disabled SELinux and was still running into the same issue. 

> This is also covered in the "Mounting the Data Directory" section of our docker documentation:

And following the steps provided in this section `--user` lead to the error above. The container is not behaving as intended. 

I also just tried using the user flag on another Ubuntu 20 server and got the following:

`Could not read telemetry config: user: Current requires cgo or $USER set in environment`
