### ISSUE TITLE
Integrate rpm/deb with automated release process

### ISSUE THREAD

**Issue by tsachiherman** [algorand/go-algorand#584]
### Integrate rpm/deb with automated release process
Use the existing rpm/deb installers and copy/modify them so they could be used as part of the release process

**Comment by btoll** [comment]
Here is a list of items that need to be done (this is only a partial list):
1. Continue separating build and sign stage from test stage
1. Automate the creation of the release page.  Brian has already written a Python3 script that gets us most of the way there.
1. Currently, the rpm repository only contains the latest release.  This is by design of the current implementation but should be changed to append rather than overwrite.
1. There is a `test_release.sh` shell script that can be brought into the build pipeline.

**Comment by btoll** [comment]
Created the following subtasks:
- https://github.com/algorand/go-algorand/issues/751
- https://github.com/algorand/go-algorand/issues/752
- https://github.com/algorand/go-algorand/issues/753
- https://github.com/algorand/go-algorand/issues/755
- https://github.com/algorand/go-algorand/issues/756
- https://github.com/algorand/go-algorand/issues/757
- https://github.com/algorand/go-algorand/issues/758

**Comment by btoll** [comment]
@ian-algorand Can this be closed and possibly re-pointed?
