### ISSUE TITLE
There are 11 pages of GitHub issues, some as old as 2019. Let's clean this up?

### ISSUE THREAD

**Issue by grzracz** [algorand/go-algorand#5911]
## Problem

Nobody is going to sift through if an issue has already been submitted. Some very important issues (for dev UX) like #5250 are sitting without any action since April 2023.

## Solution

Close issues that will not be worked on. Have some plan/ask for pull requests on things that can have realistic implementations.

## Urgency

Some urgency. Having unclosed issues since 2019 looks amateurish.

**Comment by gmalouf** [comment]
Hi @grzracz,

First, thank you for your contributions to the ecosystem. We are doing our best to keep up on issues, but bandwidth-wise we cannot near term prioritize everything. I've looked at other chains github pages and see several open issues dating back to 2019, 2018 as well.

We actually had a solid debate on this several months ago - ultimately deciding to keep issues open until we can spend more time evaluating each on the merits rather than discourage people from reporting concerns (that someone else in the community may want to take on). 

Regarding specifically #5250  - that's a great call out and post-non-archival relay work this quarter we will look to get a solution to that up behind our experimental API in Algod. It got dropped during re-prioritization in the summer and lost in the shuffle a bit.
