### ISSUE TITLE
Enable telemetry regardless of logging.config availability

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#692]

**Comment by bricerisingalgorand** [comment]
Are you proposing that telemetry should be enabled by default when no logging.config is found?

**Comment by algoradam** [comment]
Telemetry is supposed to be off by default -- we don't collect any sort of user data without the user's explicit opt-in consent. This is important because (1) nonconsensual data collection is unethical and (2) there are GDPR implications.
I'm guessing this ticket is about behavior when algod is invoked with command-line flags that enable telemetry (e.g. `algod -t true`) but the logging.config file is inaccessible?

**Comment by tsachiherman** [comment]
> Telemetry is supposed to be off by default -- we don't collect any sort of user data without the user's explicit opt-in consent. This is important because (1) nonconsensual data collection is unethical and (2) there are GDPR implications.
> I'm guessing this ticket is about behavior when algod is invoked with command-line flags that enable telemetry (e.g. `algod -t true`) but the logging.config file is inaccessible?

Correct. When we have accesibility issues to logging.config, it's not clear what is the correct operation. What we've done so far was abort the algod if we can't read the logging.config due to permission issues. That would force users to either have the file accessible, or not to have it at all.
